# Task 1. Sentiment Labeling

In [1]:
# import libraries for the analysis
!pip install textblob
from textblob import TextBlob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from transformers import pipeline
import re
import warnings
warnings.filterwarnings("ignore")

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: textblob in c:\users\quality\appdata\roaming\python\python311\site-packages (0.19.0)
Requirement already satisfied: nltk>=3.9 in c:\users\quality\appdata\roaming\python\python311\site-packages (from textblob) (3.9.1)
Requirement already satisfied: click in c:\programdata\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (8.0.4)
Requirement already satisfied: joblib in c:\programdata\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in c:\programdata\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (2022.7.9)
Requirement already satisfied: tqdm in c:\programdata\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (4.65.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)

C:\ProgramData\anaconda3\Lib\site-packages\transformers\utils\generic.py:260: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(

In [2]:
# Load the dataset
df = pd.read_excel("test.xlsx")
df.head()

,Subject,body,date,from
0,EnronOptions Update!,EnronOptions Announcement\n\n\nWe have updated...,2010-05-10,sally.beck@enron.com
1,(No Subject),"Marc,\n\nUnfortunately, today is not going to ...",2010-07-29,eric.bass@enron.com
2,Phone Screen Interview - Shannon L. Burnham,"When: Wednesday, June 06, 2001 10:00 AM-11:00 ...",2011-07-25,sally.beck@enron.com
3,RE: My new work email,we were thinking papasitos (we can meet somewh...,2010-03-25,johnny.palmer@enron.com
4,Bet,Since you never gave me the $20 for the last t...,2011-05-21,lydia.delgado@enron.com

In [3]:
print(df.columns)
df.shape

Index(['Subject', 'body', 'date', 'from'], dtype='object')

(2191, 4)

In [4]:
# clean and preprocess dataset

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'\W', ' ', text)  # Remove special characters
    text = re.sub(r'\s+', ' ', text).strip()  # Remove extra spaces
    return text
df["body"] = df["body"].apply(clean_text)

In [5]:
def label_sentiment(text):
    polarity = TextBlob(text).sentiment.polarity
    if polarity > 0.08:
        return 'Positive'
    elif polarity < -0.08:
        return 'Negative'
    else:
        return 'Neutral'

# Ensure Subject and body are treated as strings
df['text'] = df['Subject'].fillna('').astype(str) + " " + df['body'].fillna('').astype(str)

# Apply sentiment function
df['sentiment'] = df['text'].apply(label_sentiment)

In [6]:
df

,Subject,body,date,from,text,sentiment
0,EnronOptions Update!,enronoptions announcement we have updated the ...,2010-05-10,sally.beck@enron.com,EnronOptions Update! enronoptions announcement...,Positive
1,(No Subject),marc unfortunately today is not going to work ...,2010-07-29,eric.bass@enron.com,(No Subject) marc unfortunately today is not g...,Neutral
2,Phone Screen Interview - Shannon L. Burnham,when wednesday june 06 2001 10 00 am 11 00 am ...,2011-07-25,sally.beck@enron.com,Phone Screen Interview - Shannon L. Burnham w...,Neutral
3,RE: My new work email,we were thinking papasitos we can meet somewhe...,2010-03-25,johnny.palmer@enron.com,RE: My new work email we were thinking papasit...,Neutral
4,Bet,since you never gave me the 20 for the last ti...,2011-05-21,lydia.delgado@enron.com,Bet since you never gave me the 20 for the las...,Neutral
...,...,...,...,...,...,...
2186,Re: Resume,thanks for the resume she has had some good ex...,2011-06-17,johnny.palmer@enron.com,Re: Resume thanks for the resume she has had s...,Positive
2187,"Final Schedule - Wednesday, May 2, 2001 - Jesu...",attached please find the following documents t...,2011-01-20,johnny.palmer@enron.com,"Final Schedule - Wednesday, May 2, 2001 - Jesu...",Neutral
2188,(No Subject),good to finally hear from judging from your e ...,2011-01-02,don.baughman@enron.com,(No Subject) good to finally hear from judging...,Positive
2189,League is Set,it looks like we have our 12 teams we will pro...,2011-03-11,rhonda.denton@enron.com,League is Set it looks like we have our 12 tea...,Neutral
2190,AirCard Activation,we will need this so i am sending it to you as...,2010-10-30,johnny.palmer@enron.com,AirCard Activation we will need this so i am s...,Neutral

In [8]:
# Save updated dataset
df.to_csv("test_labeled.csv", index=False)
print("Sentiment labeling complete. Saved as test_labeled.csv.")

Sentiment labeling complete. Saved as test_labeled.csv.